apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  database.password: ZGJfMTIz
  POSTGRES_PASSWORD: ZGJfMTIz
  POSTGRES_DB: bmFncF9tZW1iZXJfZGI=
  POSTGRES_USER: cmFodWw=
  POSTGRES_HOST: cG9zdGdyZXMtc2VydmljZQ==
